/**:
  ros__parameters:
    lio.map.save_map: false
    lio.map.if_filter: true
    lio.map.save_map_dir: "map"
    lio.map.map_name: "map.pcd"
    lio.map.ds_size: 0.3
    lio.map.save_interval: 500

    lio.ros.lidar_topic: "/velodyne_points"
    lio.ros.imu_topic: "/vectornav/imu"

    lio.sensor.lidar_type: 4
    lio.sensor.blind: 1.0
    lio.sensor.maxrange: 100.0
    lio.sensor.filter_rate: 1
    lio.sensor.enable_downsample: true
    lio.sensor.voxel_fliter_size: 0.4
    lio.sensor.gravity_norm: 9.7946
    lio.sensor.imu_type: 0
    lio.sensor.imu_na: 0.004
    lio.sensor.imu_ng: 0.0015
    lio.sensor.imu_nba: 0.00006
    lio.sensor.imu_nbg: 0.00003

    lio.extrinsic.lidar_imu:
      [-0.201, 0.096, 0.014, -1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0]

    lio.extrinsic.odom_robo: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    lio.hash_map.hash_capacity: 1000000
    lio.hash_map.vox_resolution: 0.5

    lio.kf.kf_type: 0
    lio.kf.kf_max_iterations: 4
    lio.kf.kf_align_gravity: true
    lio.kf.kf_quit_eps: 0.001

    lio.output.robot: true
    lio.output.plan_env_world: false
    lio.output.plan_env_body: false
    lio.output.ml_map: false
    lio.output.planner: false
    lio.output.map: true
    lio.output.dense: false
    lio.output.pub_step: 1

    lio.eva.timer: true

    # Surrounding map
    lio.loop_closure.surrounding_keyframe_adding_dist_threshold: 0.5   # meters, regulate keyframe adding threshold
    lio.loop_closure.surrounding_keyframe_adding_angle_threshold: 0.2  # radians, regulate keyframe adding threshold
    lio.loop_closure.surrounding_keyframe_density: 2.0                 # meters, downsample surrounding keyframe poses
    lio.loop_closure.surrounding_keyframe_search_radius: 50.0          # meters, within n meters scan-to-map optimization
                                                                        # (when loop closure disabled)

    # Loop closure
    lio.loop_closure.enable: true
    lio.loop_closure.frequency: 2.0           # Hz, regulate loop closure constraint add frequency
    lio.loop_closure.surrounding_keyframe_size: 10  # submap size (when loop closure enabled)
    lio.loop_closure.history_keyframe_search_radius: 40.0   # meters, key frame within n meters will be considered
    lio.loop_closure.history_keyframe_search_time_diff: 10.0 # seconds, key frame n seconds older will be considered
    lio.loop_closure.history_keyframe_search_num: 50         # number of history key frames fused into submap
    lio.loop_closure.history_keyframe_fitness_score: 0.5     # icp threshold, the smaller the better alignment
